### ISSUE TITLE
OIDC Gatekeeper breaks when using a custom CA

### ISSUE THREAD

**Issue by grobbie** [canonical/oidc-gatekeeper-operator#15]
When using a self-signed certificate or a custom CA/trust chain for the front-end (for example when putting HAproxy  in front of Kubeflow), OIDC Gatekeeper blows up because it doesn't trust the server certificate issuer.

OIDC Gatekeeper supports the `CA_BUNDLE` environment variable which can contain the path to a PEM file containing the trust chain certificate bundle, however this is not being set in the pod, and there is no JuJu action to install a custom trust chain PEM file.

This is needed in order to use CKF in environments that have a dedicated internal CA service.

**Comment by grobbie** [comment]
Also broken when using an ingress directly...

```sh
microk8s.kubectl create -n kubeflow secret tls kubeflow-credential --key=kubeflow.ubuntu.local.key --cert=kubeflow.ubuntu.local.crt
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-ingress-ssl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  tls:
    - hosts:
      - kubeflow.ubuntu.local
      secretName: kubeflow-credential
  rules:
  - host: kubeflow.ubuntu.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: istio-ingressgateway
              port:
                number: 80
```

```sh
microk8s.kubectl get ingress -nkubeflow
NAME                   CLASS    HOSTS                   ADDRESS     PORTS     AGE
kubeflow-ingress-ssl   public   kubeflow.ubuntu.local   127.0.0.1   80, 443   4m27s
```

```sh
microk8s.kubectl logs  -nkubeflow oidc-gatekeeper-cb956fdb8-ncblp
time="2022-02-01T13:24:34Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get https://kubeflow.ubuntu.local/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority"
time="2022-02-01T13:24:44Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get https://kubeflow.ubuntu.local/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority"
time="2022-02-01T13:24:54Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get https://kubeflow.ubuntu.local/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority"
...
```
